language: php

php:
  - 5.5
  - 5.6
  - 7.0

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.1.1"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --dev --prefer-dist --no-interaction
  - cd tests && ../vendor/codeception/codeception/codecept build

before_script:
  - mysql -e 'create database database;'  
  - |
    if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
      CODECEPT_FLAGS=" --coverage --coverage-xml"
    fi
script:
  - cd tests && ..vendor/codeception/codeception/codecept run unit --verbose $CODECEPT_FLAGS

after_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
      bash <(curl -s https://codecov.io/bash)
    fi